name: Maven Package

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       #working-directory: ./s3-processor   
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build a package
      run: mvn clean install -DskipTests

    - name: Docker build
      run: |
        docker build . -t jaiobs/maven-jar-sample:latest
    -   name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: vinodh.v@optisolbusiness.com
          password: ${{ secrets.TOKEN_GITHUB }}
    - name: Docker push
      run: |
        docker push jaiobs/maven-jar-sample:latest
